### ISSUE TITLE
report eigvalsh() bug to SciPy

### ISSUE THREAD

**Issue by bukov** [weinbe58/qspin#3]
The following error appeared when running example0.py with L=16:

```
mbukov@wireless1x-155-41-120-89:~/ED_python/qspin_paper/scripts$ pythonw example0.py 

Hermiticity check passed!

Symmetry checks passed!

Particle conservation check passed!

Traceback (most recent call last):

  File "example0.py", line 28, in <module>

    E=H_XXZ.eigvalsh()

  File "/Users/mbukov/anaconda2/lib/python2.7/site-packages/qspin/operators/ops.py", line 979, in eigvalsh

    E = _la.eigvalsh(H_dense,**eigvalsh_args)

  File "/Users/mbukov/anaconda2/lib/python2.7/site-packages/scipy/linalg/decomp.py", line 684, in eigvalsh

    check_finite=check_finite)

  File "/Users/mbukov/anaconda2/lib/python2.7/site-packages/scipy/linalg/decomp.py", line 345, in eigh

    iu=a1.shape[0], overwrite_a=overwrite_a)

ValueError: On entry to DSBRDB parameter number 12 had an illegal value
```

**Comment by mgbukov** [comment]
Issue reported:

https://github.com/scipy/scipy/issues/8205#issuecomment-350194073

**Comment by empyriumz** [comment]
Hi @mgbukov 

Is any update about fixing this bug? I have tried a workaround to install the open-blas based Numpy instead of MKL before but now when installing QuSpin via conda it automatically replaces the blas version to MKL one.

**Comment by mgbukov** [comment]
The issue in scipy (see link above) is still open. I think it hasn't been resolved yet. I think scipy are waiting for MKL, and we're waiting for scipy down the chain.

In the time being, you can use the `eigsh()` function method which does not suffer from this issue, if I remember correctly.

**Comment by empyriumz** [comment]
> The issue in scipy (see link above) is still open. I think it hasn't been resolved yet. I think scipy are waiting for MKL, and we're waiting for scipy down the chain.
> 
> In the time being, you can use the `eigsh()` function method which does not suffer from this issue, if I remember correctly.

I'll have a try using eigsh(), thanks!
